/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Suite */
        post: operations["create_suite_api_suites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suites/{suite_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Suite */
        get: operations["stream_suite_api_suites__suite_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Options */
        get: operations["get_options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateResult */
        CandidateResult: {
            /** Candidate Id */
            candidate_id: number;
            /** Final Code */
            final_code: string;
            /** Converged */
            converged: boolean;
            /** Iterations Used */
            iterations_used: number;
            /** Error History */
            error_history: components["schemas"]["IterationRecord"][];
        };
        /** CompleteEvent */
        CompleteEvent: {
            /** @default complete */
            type: components["schemas"]["EventType"];
            result: components["schemas"]["PipelineResult"];
        };
        /** ErrorEvent */
        ErrorEvent: {
            /** @default error */
            type: components["schemas"]["EventType"];
            /** Message */
            message: string;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "progress" | "complete" | "error";
        /** ExperimentRequest */
        ExperimentRequest: {
            generation: components["schemas"]["StageRequest"];
            correction?: components["schemas"]["StageRequest"] | null;
            /** Num Candidates */
            num_candidates?: number | null;
            /** Max Iterations */
            max_iterations?: number | null;
            /** Save Intermediates */
            save_intermediates?: boolean | null;
            /** Stop On First Convergence */
            stop_on_first_convergence?: boolean | null;
            /** Name */
            name: string;
        };
        /**
         * ExperimentResult
         * @description The outcome of one named experiment in a suite.
         *
         *     Holds the full per-run ``PipelineResult`` unchanged; comparison metrics are
         *     derived from it at write/display time rather than baked into the model, so
         *     adding a metric never requires re-running a suite.
         */
        ExperimentResult: {
            /** Name */
            name: string;
            result: components["schemas"]["PipelineResult"];
        };
        /** GenerateRequest */
        GenerateRequest: {
            generation: components["schemas"]["StageRequest"];
            correction?: components["schemas"]["StageRequest"] | null;
            /** Num Candidates */
            num_candidates?: number | null;
            /** Max Iterations */
            max_iterations?: number | null;
            /** Save Intermediates */
            save_intermediates?: boolean | null;
            /** Stop On First Convergence */
            stop_on_first_convergence?: boolean | null;
            /** Contract Text */
            contract_text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IterationRecord */
        IterationRecord: {
            /** Iteration */
            iteration: number;
            /** Code */
            code: string;
            /** Errors */
            errors: components["schemas"]["SymboleoIssue"][];
            usage?: components["schemas"]["TokenUsage"] | null;
        };
        /** OptionsResponse */
        OptionsResponse: {
            /** Strategies */
            strategies: string[];
            /** Models */
            models: {
                [key: string]: string[];
            };
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Examples */
            examples: string[];
        };
        /** PipelineResult */
        PipelineResult: {
            /** Success */
            success: boolean;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Input File */
            input_file: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateResult"][];
        };
        /** ProgressEvent */
        ProgressEvent: {
            /** @default progress */
            type: components["schemas"]["EventType"];
            /** Experiment Index */
            experiment_index?: number | null;
            /** Candidate Id */
            candidate_id: number;
            /** Iteration */
            iteration: number;
            /** Error Count */
            error_count: number;
        };
        /** RunCreatedResponse */
        RunCreatedResponse: {
            /** Run Id */
            run_id: string;
            /** Warnings */
            warnings?: string[];
        };
        /** StageRequest */
        StageRequest: {
            /** Model */
            model: string;
            /** Strategy */
            strategy: string;
            /** Temperature */
            temperature?: number | null;
            /** Include Grammar */
            include_grammar?: boolean | null;
            /** Strategy Params */
            strategy_params?: {
                [key: string]: unknown;
            };
        };
        /** SuiteCompleteEvent */
        SuiteCompleteEvent: {
            /** @default complete */
            type: components["schemas"]["EventType"];
            result: components["schemas"]["SuiteResult"];
        };
        /** SuiteRequest */
        SuiteRequest: {
            /** Contract Text */
            contract_text: string;
            /** Experiments */
            experiments: components["schemas"]["ExperimentRequest"][];
        };
        /** SuiteResult */
        SuiteResult: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Input File */
            input_file: string;
            /** Experiments */
            experiments: components["schemas"]["ExperimentResult"][];
        };
        /** SymboleoIssue */
        SymboleoIssue: {
            /** Severity */
            severity: string;
            /** Code */
            code: string | null;
            /** Offset */
            offset: number;
            /** Line */
            line: number;
            /** Column */
            column: number;
            /** Length */
            length: number;
            /** Message */
            message: string;
        };
        /**
         * TokenUsage
         * @description Token counts and cost for a single LLM call.
         *
         *     Attached to each ``IterationRecord`` (one call per iteration). Per-candidate
         *     and per-experiment totals are derived from these by summing, never stored —
         *     consistent with the "metrics are derived, not stored" rule. ``cost_usd`` is
         *     best-effort: ``None`` when LiteLLM has no pricing for the model.
         */
        TokenUsage: {
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Total Tokens
             * @description Always prompt + completion — derived rather than trusting the reported total.
             */
            readonly total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_api_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_suite_api_suites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuiteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressEvent"] | components["schemas"]["CompleteEvent"] | components["schemas"]["ErrorEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_suite_api_suites__suite_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressEvent"] | components["schemas"]["SuiteCompleteEvent"] | components["schemas"]["ErrorEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsResponse"];
                };
            };
        };
    };
}
